config/routes.rb
Rails.application.routes.draw do
  resources :users do
    collection do
      get 'multiple_actions'
    end
  end
  resources :users, only: [:new, :create]
  get '/sign_up', to: 'users#new', as: :sign_up
  root to: 'users#show'
  get '/block', to: 'users#block'
  resources :sessions, only: [:new, :create, :destroy]
  get '/log_in', to: 'sessions#new', as: :log_in
  delete '/log_out', to: 'sessions#destroy', as: :log_out
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  validates :password, length: { minimum: 1 }
  validates :password, confirmation: true
  validates :email, uniqueness: true, email_format: { message: 'has invalid format' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  private

  def not_authenticated
    flash[:warning] = 'You have to authenticate to access this page.'
    redirect_to log_in_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]

  def new
  end

  def create
    if login(params[:email], params[:password])
      flash[:success] = 'Welcome back!'
      redirect_to root_path
    else
      flash.now[:warning] = 'E-mail and/or password is incorrect.'
      render 'new'
    end
  end

  def destroy
    logout
    flash[:success] = 'See you!'
    redirect_to log_in_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def show
    redirect_to block_path if current_user.block
    @users = User.all
  end

  def block
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(params[:user][:email], params[:user][:password])
      flash[:success] = 'Welcome!'
      redirect_to root_path
    else
      flash.now[:alert] = 'Login failed'
      render 'new'
    end
  end

  def multiple_actions
    unless params[:user_id].nil?
      method_name = params[:commit].downcase.tr(' ', '_')
      public_send(method_name, params)
    end
    redirect_to root_path
  end

  def delete_selected(params)
      params[:user_id].each do |user_id|
        User.find(user_id).destroy
        session[user_id] = nil
      end
  end

  def unblock_selected(params)
      params[:user_id].each do |user_id|
        @user = User.find(user_id)
        @user.update_column(:block, false)
      end
  end

  def block_selected(params)
      params[:user_id].each do |user_id|
        @user = User.find(user_id)
        @user.update_column(:block, true)
        session[user_id] = nil
      end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Progect</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <% if current_user %>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal">Iransition Task 4</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <span><%= "You login as " + current_user.name %></span>
      </nav>
      <%= link_to 'Log Out', log_out_url,:class => 'btn btn-btn btn-primary btn-xs', method: :delete %>
    </div>
    <% end %>

    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/users/block.html.erb
<h1>Your account has blocked</h1>

app/views/users/new.html.erb
<h1>Registration</h1>

<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control', required: true %>
  </div>
  <%= f.submit 'Register', class: 'btn btn-primary btn-lg' %>
  <div id="navbar">
    <ul class="nav navbar-nav">
      <li><%= link_to 'Log In', log_in_path %></li>
    </ul>
  </div>
<% end %>

app/views/users/show.html.erb
<%= form_tag multiple_actions_users_url, method: :get do %>
<%= submit_tag "Unblock Selected", :class => 'btn mb-3 btn-success toolbar' %>
<%= submit_tag "Block Selected", :class => 'btn mb-3 btn-warning toolbar' %>
<%= submit_tag "Delete Selected", :class => 'btn mb-3 btn-danger toolbar' %>
<table class="footable table table-bordered toggle-arrow-tiny" data-page-size="31" data-filter=#filter>
<thead>
  <tr>
    <th data-sort-ignore="true"><input type="checkbox" id="select-all"> Select All</input></th>
    <th>User ID</th>
    <th>User Name</th>
    <th>Email</th>
    <th>Last login at</th>
    <th>Status</th>
  </tr>
</thead>

<tbody>
  <% @users.each do |item| %>
  <tr>
    <td><%= check_box_tag "user_id[]", item.id, false, class: 'selectable' %></td>
    <td><%= item.id %></td>
    <td><%= item.name %></td>
    <td><%= item.email %></td>
    <td><%= item.last_login_at.to_s %></td>
    <% if item.block %>
      <td>Blocked</td>
    <% else %>
      <td>Active</td>
    <% end %>
  </tr>
<% end %>
</tbody>
<tfoot>
<tr>
    <td colspan="12">
 <ul class="pagination pull-right"></ul>
    </td>
</tr>
</tfoot>
<% end %>